// js/links-data.js
// Add new entries here. The Links page can sort/render these automatically.

var GAME_LINKS = [
  { title: "Acting Lessons", platform: "steam", url: "https://store.steampowered.com/app/1045520/Acting_Lessons/", tags: ["visual novel"] },
  { title: "After the Inferno", platform: "steam", url: "https://store.steampowered.com/app/2027360/After_the_Inferno/", tags: ["visual novel"] },
  { title: "Ark Re:Code", platform: "steam", url: "https://store.steampowered.com/app/3587140/Ark_ReCode/", tags: ["visual novel"] },
  { title: "Being a DIK", platform: "steam", url: "https://store.steampowered.com/app/1126320/Being_a_DIK__Season_1/", tags: ["visual novel"] },
  { title: "B.E.S.T.", platform: "steam", url: "https://store.steampowered.com/app/2404390/BEST/", tags: ["visual novel"] },
  { title: "Chasing Sunsets", platform: "steam", url: "https://store.steampowered.com/app/1783110/Chasing_Sunsets/", tags: ["visual novel"] },
  { title: "Cozy Cafe", platform: "itch", url: "https://cosy-creator.itch.io/cosy-cafe", tags: ["visual novel"] },
  { title: "Eternum", platform: "itch", url: "https://caribdis.itch.io/eternum", tags: ["visual novel"] },
  { title: "Fresh Women Season 2", platform: "steam", url: "https://store.steampowered.com/app/3478650/FreshWomen__Season_2/" },
  { title: "Leap of Faith", platform: "steam", url: "https://store.steampowered.com/app/1768640/Leap_of_Faith/" },
  { title: "Quickie: Fantasy Adventure", platform: "itch", url: "https://oppaigames.itch.io/quickie-fantasy-adventure" },
  { title: "Race of Life", platform: "steam", url: "https://store.steampowered.com/app/2454570/Race_of_Life__Act_1/" },
  { title: "Chasing Tails", platform: "steam", url: "https://store.steampowered.com/app/1555110/Chasing_Tails_A_Promise_in_the_Snow/" },
  { title: "City of Broken Dreamers", platform: "steam", url: "https://store.steampowered.com/app/1358250/City_of_Broken_Dreamers_Book_One/" },
  { title: "Cockwork Industries Complete", platform: "steam", url: "https://store.steampowered.com/app/1172940/Cockwork_Industries_Complete/" },
  { title: "College Kings", platform: "steam", url: "https://store.steampowered.com/app/1463120/College_Kings__The_Complete_Season/" },
  { title: "College Kings 2", platform: "steam", url: "https://store.steampowered.com/app/1924480/College_Kings_2__Episode_1/" },
  { title: "Dreamland", platform: "steam", url: "https://store.steampowered.com/app/2176560/Dreamland/" },
  { title: "Femboy Futa House", platform: "steam", url: "https://store.steampowered.com/app/3602290/FEMBOY_FUTA_HOUSE/" },
  { title: "Fetish Locator", platform: "steam", url: "https://store.steampowered.com/app/1360980/Fetish_Locator_Week_One/" },
  { title: "Fresh Women", platform: "steam", url: "https://store.steampowered.com/app/1350650/FreshWomen__Season_1/" },
  { title: "Futanari di Funghi", platform: "steam", url: "https://store.steampowered.com/app/2496640/Futanari_di_Funghi/" },
  { title: "Gray", platform: "steam", url: "https://store.steampowered.com/app/1034700/GRAY/", tags: ["pixel"] },
  { title: "Handyman Legend", platform: "steam", url: "https://store.steampowered.com/app/2127010/Handyman_Legend/" },
  { title: "Hentai Hack-Her", platform: "steam", url: "https://store.steampowered.com/app/1596980/Hentai_HackHer/" },
  { title: "Her New Memory", platform: "steam", url: "https://store.steampowered.com/app/1296770/Her_New_Memory__Hentai_Simulator/" },
  { title: "HunieCam Studio", platform: "steam", url: "https://store.steampowered.com/app/426000/HunieCam_Studio/" },
  { title: "Innocence or Money", platform: "steam", url: "https://store.steampowered.com/app/1722270/Innocence_Or_Money__Prelude/" },
  { title: "Kiara and My Ara Ara Adventure", platform: "steam", url: "https://store.steampowered.com/app/1343090/Kiara_And_My_Ara_Ara_Adventure/" },
  { title: "Kidnapped Girl", platform: "steam", url: "https://store.steampowered.com/app/1274290/Kidnapped_Girl/" },
  { title: "Last Evil", platform: "steam", url: "https://store.steampowered.com/app/823910/Last_Evil/" },
  { title: "Lollipop!", platform: "steam", url: "https://store.steampowered.com/app/1515230/LOLLIPOP/" },
  { title: "Hero by Chance", platform: "steam", url: "https://store.steampowered.com/app/1433420/Love_n_War_Hero_by_Chance/" },
  { title: "Love Sucks: Night One", platform: "steam", url: "https://store.steampowered.com/app/1577420/Love_Sucks_Night_One/" },
  { title: "LoveKami -Useless Goddess-", platform: "steam", url: "https://store.steampowered.com/app/626510/LoveKami_Useless_Goddess/" },
  { title: "Lucy Got Problems", platform: "steam", url: "https://store.steampowered.com/app/879510/Lucy_Got_Problems/" },
  { title: "Lunar's Chosen: Episode 1", platform: "steam", url: "https://store.steampowered.com/app/1695680/Lunars_Chosen__Episode_1/" },
  { title: "Lust Academy", platform: "steam", url: "https://store.steampowered.com/app/1846920/Lust_Academy__Season_1/" },
  { title: "Lust Epidemic", platform: "steam", url: "https://store.steampowered.com/app/1008020/Lust_Epidemic/" },
  { title: "Lust Goddess", platform: "steam", url: "https://store.steampowered.com/app/2808930/Lust_Goddess/" },
  { title: "Midnight Ride", platform: "steam", url: "https://store.steampowered.com/app/1210110/Midnight_Ride/" },
  { title: "MILF's Plaza", platform: "steam", url: "https://store.steampowered.com/app/2706300/MILFs_Plaza/" },
  { title: "Milfy City", platform: "steam", url: "https://store.steampowered.com/app/2544090/Milfy_City__Final_Edition/" },
  { title: "Overlewd", platform: "steam", url: "https://store.steampowered.com/app/2308870/Overlewd/" },
  { title: "Phantom Thief Effie", platform: "steam", url: "https://store.steampowered.com/app/2407550/Phantom_Thief_Effie/" },
  { title: "Private Dorm Manager", platform: "steam", url: "https://store.steampowered.com/app/2273420/Private_Dorm_Manager/" },
  { title: "Space Rescue", platform: "steam", url: "https://store.steampowered.com/app/1407210/Space_Rescue_Code_Pink/" },
  { title: "Subverse", platform: "steam", url: "https://store.steampowered.com/app/1034140/Subverse/" },
  { title: "Succubus Waifu", platform: "steam", url: "https://store.steampowered.com/app/1184400/Succubus_Waifu/" },
  { title: "Treasure of Nadia", platform: "steam", url: "https://store.steampowered.com/app/1737100/Treasure_of_Nadia/" },
  { title: "U4iA", platform: "steam", url: "https://store.steampowered.com/app/2890150/U4iA__Season_1/" },
  { title: "Devious Demigods", platform: "itch", url: "https://kraytstudios.itch.io/devious-demigods" },
  { title: "My Pig Princess", platform: "itch", url: "https://cyancapsule.itch.io/my-pig-princess" },
  { title: "Deluded", platform: "itch", url: "https://deludedgame.itch.io/deluded" },
  { title: "Succum Brewery", platform: "itch", url: "https://succumdev.itch.io/succum-brewery" },
  { title: "Mist", platform: "itch", url: "https://395games.itch.io/mist-free" },
  { title: "Goodbye Eternity", platform: "itch", url: "https://the-end-of-time.itch.io/goodbye-eternity-demo" },
  { title: "Welcum to the City", platform: "itch", url: "https://quiquersson.itch.io/w2c-free" },
  { title: "Lusty Buccaneers", platform: "itch", url: "https://nika-dev.itch.io/lusty-buccaneers" },
  { title: "Ripples", platform: "itch", url: "https://jestur.itch.io/ripples" }
];

